ProyectoFinal/Blog/urls.py
from django.urls import path
from Blog import views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path("", views.inicio, name="Inicio"),
    path("sobreNosotros/", views.sobreNostros, name="sobreNosotros"),
    path("hacerPosteo/", views.hacerPosteo, name="hacerPosteo"),
    path("posteo/<titulo>", views.abrirPosteo, name="Posteo"),
    path("buscar/", views.buscar, name="Buscar"),
    path("register/", views.registro, name="Register"),
    path("login/", views.iniciarSesion, name="Login"),
    path(
        "logout/", LogoutView.as_view(template_name="Blog/logout.html"), name="Logout"
    ),
    path("listaPosteos/", views.listarPosteos, name="listaPosteos"),
    path("borrarPosteo/<posteo_titulo>", views.borrarPosteos, name="borrarPosteo"),
    path("editarPosteo/<posteo_titulo>", views.editarPosteos, name="editarPosteo"),
    path("editarUsuario/", views.editarUsuario, name="editarUsuario"),
    path("agregarAvatar/", views.agregarAvatar, name="agregarAvatar"),
]

ProyectoFinal/ProyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("Blog.urls")),
    path("Blog/", include("Blog.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoFinal/Blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Usuario(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    dni = models.IntegerField(primary_key=True)

    def __str__(self):
        return f"{self.dni} | {self.nombre} {self.apellido}"


class Posteo(models.Model):

    autor = models.CharField(max_length=40)
    email = models.EmailField()
    fecha = models.DateField(auto_now_add=True)
    titulo = models.CharField(max_length=40, primary_key=True)
    cuerpo = models.TextField("")
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.titulo} | {self.autor}"


class Comentario(models.Model):

    autor = models.CharField(max_length=40)
    email = models.EmailField()
    cuerpo = models.TextField("")
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.autor} | {self.fecha}"


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

    def __str__(self):
        return f"{self.user} | {self.imagen}"

    class Meta:
        verbose_name = "Avatar"
        verbose_name_plural = "Avatares"


class Perfil(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)

ProyectoFinal/Blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from Blog.models import Avatar


class FormularioPosteo(forms.Form):

    autor = forms.CharField(max_length=40)
    email = forms.EmailField()
    titulo = forms.CharField(max_length=40)
    cuerpo = forms.CharField(widget=forms.Textarea)
    imagen = forms.ImageField()


class FormularioBusqueda(forms.Form):

    titulo = forms.CharField(max_length=40)


class FormularioRegistroUsuario(UserCreationForm):

    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Confirme su contraseña", widget=forms.PasswordInput
    )

    class Meta:

        model = User
        fields = ["username", "password1", "password2"]
        help_texts = {"username": None, "password1": None, "password2": None}


class AvatarFormulario(forms.ModelForm):
    class Meta:

        model = Avatar
        fields = ["user", "imagen"]


class UserEditionForm(UserCreationForm):
    first_name = forms.CharField(label="Nombre")
    last_name = forms.CharField(label="Apellido")
    email = forms.EmailField(label="Modificar email")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "password1", "password2"]
        help_texts = {k: "" for k in fields}

ProyectoFinal/Blog/views.py
from django.shortcuts import redirect, render
from Blog.forms import (
    FormularioPosteo,
    FormularioRegistroUsuario,
    AvatarFormulario,
    UserEditionForm,
)
from Blog.models import Avatar, Posteo, Comentario, Perfil
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

# Vista Inicio
def inicio(request):

    id = 1
    listadoPosteos = Posteo.objects.all()
    diccionario = {"id": id, "listadoPosteos": listadoPosteos}
    return render(request, "Blog/inicio.html", diccionario)


# Vista Sobre Nosotros
def sobreNostros(request):

    id = 2
    diccionario = {"id": id}
    return render(request, "Blog/sobreNosotros.html", diccionario)


# Vista para hacer un posteo
@login_required
def hacerPosteo(request):

    if request.method == "POST":

        miPosteo = FormularioPosteo(request.POST, request.FILES)

        print(miPosteo)

        if miPosteo.is_valid():

            contenido = miPosteo.cleaned_data

            posteo = Posteo(
                autor=contenido["autor"],
                email=contenido["email"],
                titulo=contenido["titulo"],
                cuerpo=contenido["cuerpo"],
                imagen=contenido["imagen"],
            )

            posteo.save()

            listadoPosteos = Posteo.objects.all()
            return render(
                request,
                "Blog/inicio.html",
                {"mensaje": f"¡Posteo creado!", "listadoPosteos": listadoPosteos},
            )
    else:

        miPosteo = FormularioPosteo()

    id = 3
    diccionario = {"id": id, "miPosteo": miPosteo}
    return render(request, "Blog/hacerPosteo.html", diccionario)


# Vista para buscar un posteo
def buscar(request):

    data = request.GET.get("titulo", "")

    error = ""

    if data:

        try:
            posteo = Posteo.objects.get(titulo=data)
            return render(
                request, "Blog/buscar.html", {"posteo": posteo, "titulo": data}
            )

        except Exception as exc:
            print(exc)
            error = "¡No se encontraron posteos con el título indicado!"

    id = 4
    diccionario = {"id": id, "error": error}
    return render(request, "Blog/buscar.html", diccionario)


# Vista para ver en detalle un posteo
def abrirPosteo(request, titulo):

    leerPosteo = Posteo.objects.get(titulo=titulo)

    try:
        comentario = Comentario.objects.get(titulo=titulo)

        return render(
            request,
            "Blog/posteo.html",
            {"posteo": leerPosteo, "comentario": comentario},
        )

    except:

        return render(request, "Blog/posteo.html", {"posteo": leerPosteo})


# Vista para iniciar sesión
def iniciarSesion(request):

    if request.method == "POST":

        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():

            usuario = form.cleaned_data.get("username")
            contra = form.cleaned_data.get("password")

            user = authenticate(username=usuario, password=contra)

            if user is not None:

                login(request, user)

                listadoPosteos = Posteo.objects.all()

                return render(
                    request,
                    "Blog/inicio.html",
                    {
                        "mensaje": f"¡Bienvenido {user}!",
                        "listadoPosteos": listadoPosteos,
                    },
                )

            else:

                return render(
                    request, "Blog/login.html", {"errors": ["El usuario no existe."]}
                )

        else:

            form = AuthenticationForm()
            return render(
                request,
                "Blog/login.html",
                {"form": form, "errors": ["¡Usuario y/o contraseña incorrectos!"]},
            )

    else:
        id = 5
        form = AuthenticationForm()
        diccionario = {"id": id, "form": form}
        return render(request, "Blog/login.html", diccionario)


# Vista para registrarse
def registro(request):

    if request.method == "POST":

        registerForm = FormularioRegistroUsuario(request.POST)

        if registerForm.is_valid():

            user = registerForm.cleaned_data["username"]

            registerForm.save()

            listadoPosteos = Posteo.objects.all()

            return render(
                request,
                "Blog/inicio.html",
                {
                    "mensaje": f"¡Usuario {user} creado!",
                    "listadoPosteos": listadoPosteos,
                },
            )

    else:

        registerForm = FormularioRegistroUsuario()
    id = 6
    diccionario = {"id": id, "registerForm": registerForm}
    return render(request, "Blog/register.html", diccionario)


# Vista para ver lista de posteos
@login_required
def listarPosteos(request):

    id = 7
    listadoPosteos = Posteo.objects.all()
    diccionario = {"id": id, "listadoPosteos": listadoPosteos}
    return render(request, "Blog/listaPosteos.html", diccionario)


# Vista para borrar un posteo
@login_required
def borrarPosteos(request, posteo_titulo):

    posteo = Posteo.objects.get(titulo=posteo_titulo)

    posteo.delete()

    id = 7
    listadoPosteos = Posteo.objects.all()
    diccionario = {"id": id, "listadoPosteos": listadoPosteos}
    return render(request, "Blog/listaPosteos.html", diccionario)


# Vista para editar un posteo
@login_required
def editarPosteos(request, posteo_titulo):

    posteo = Posteo.objects.get(titulo=posteo_titulo)

    if request.method == "POST":

        editForm = FormularioPosteo(request.POST, request.FILES)

        if editForm.is_valid():

            contenido = editForm.cleaned_data

            posteo.autor = contenido["autor"]
            posteo.email = contenido["email"]
            posteo.titulo = contenido["titulo"]
            posteo.cuerpo = contenido["cuerpo"]
            posteo.imagen = contenido["imagen"]
            posteo.save()

            listadoPosteos = Posteo.objects.all()
            return render(
                request,
                "Blog/inicio.html",
                {"mensaje": f"¡Posteo Editado!", "listadoPosteos": listadoPosteos},
            )
    else:

        editForm = FormularioPosteo(
            initial={
                "autor": posteo.autor,
                "email": posteo.email,
                "titulo": posteo.titulo,
                "cuerpo": posteo.cuerpo,
            }
        )

    id = 8
    diccionario = {"id": id, "editForm": editForm, "posteo_titulo": posteo_titulo}
    return render(request, "Blog/editarPosteo.html", diccionario)


# Vista para editar un usuario
@login_required
def editarUsuario(request):

    usuario = request.user

    if request.method == "POST":

        editForm = UserEditionForm(request.POST)

        if editForm.is_valid():

            contenido = editForm.cleaned_data
            usuario.first_name = contenido["first_name"]
            usuario.last_name = contenido["last_name"]
            usuario.email = contenido["email"]
            usuario.password1 = contenido["password1"]
            usuario.password2 = contenido["password2"]
            usuario.save()

            listadoPosteos = Posteo.objects.all()
            return render(
                request,
                "Blog/inicio.html",
                {
                    "mensaje": f"¡Usuario {usuario.username} Editado!",
                    "listadoPosteos": listadoPosteos,
                },
            )
    else:

        editForm = UserEditionForm(initial={"username": usuario.username})

    id = 9
    diccionario = {"id": id, "editForm": editForm, "usuario": usuario.username}
    return render(request, "Blog/editarUsuario.html", diccionario)


# Vista para subir avatar
@login_required
def agregarAvatar(request):

    if request.method == "POST":

        form = AvatarFormulario(request.POST, request.FILES)

        if form.is_valid():

            contenido = form.cleaned_data

            avatar = Avatar(user=contenido["user"], imagen=contenido["imagen"])

            avatar.save()

            listadoPosteos = Posteo.objects.all()
            return render(
                request,
                "Blog/inicio.html",
                {"mensaje": f"¡Avatar Agregado!", "listadoPosteos": listadoPosteos},
            )

    else:

        form = AvatarFormulario()

    id = 10
    diccionario = {"id": id, "form": form}
    return render(request, "Blog/agregarAvatar.html", diccionario)

ProyectoFinal/Blog/templates/Blog/agregarAvatar.html
{% extends 'Blog/padre.html' %}

{% load static %}

{% block titulo_header %}
    <div class="tituloHeader">
        <span class='subheading'>Subi tu avatar!</span>
    </div>
    <div class="parrafo">
        <p>En el apartado de abajo podras subir la imagen de perfil que quieras </p>
    </div>

{% endblock %}

{% block contenido_principal %}

    {% if form.errors %}

        <p style='color: red; text-align: center'>¡Datos incorrectos!</p>

    {% endif %}
    <br>
    <br>
        <div class='mb-4'>
            <div class='container px-4 px-lg-5'>
                <form class='form-group text-center' action='' method='POST' enctype='multipart/form-data'>{% csrf_token %}
                    <table class='table'>
                        {{form.as_p}}
                    </table>
                    <input type='submit' value='SUBIR AVATAR' class='btn btn-dark mx-1'>
                    <button type='button' class='btn btn-dark position-relative'>
                        <a href='{% url "Inicio" %}' style='color: white;'>IR A INICIO</a>
                    </button>
                </form>
            </div>
        </div>

{% endblock %}

ProyectoFinal/Blog/templates/Blog/buscar.html
{% extends 'Blog/padre.html' %}

{% load static %}

{% block contenido_avatar %}

    <img class='mx-2' height='50px' src='{{url}}' alt='Avatar' title='Avatar'>

{% endblock %}

{% block titulo_header %}

    <div class="tituloHeader">
        <span class='subheading'>BUSCADOR</span>
    </div>
    <div class="parrafo">
        <p>En el buscador de abajo podras encontrar por titulo la historia que desees</p>
    </div>
    <form action='/Blog/buscar' method='GET'>
        <div class='form-floating'>
            <input class='form-control' type='text' name='titulo' placeholder='Ingrese un título...'>
            <label for='titulo'>Título</label>
        </div>
        <input type='submit' value='BUSCAR' class='btn btn-dark mt-3'>
        <button type='button' class='btn btn-dark position-relative mt-3 mx-2'>
            <a href='{% url "Inicio" %}' style='color: white;'>IR A INICIO</a>
        </button>
    </form>

{% endblock %}

{% block contenido_principal %}
<!--     <br>
    <br>
    <main class='mb-3'>
        <div class='container px-4 px-lg-5'>
            <div class='row gx-4 gx-lg-5 justify-content-center'>
                <div class='col-md-10 col-lg-8 col-xl-7'>
                    <h2>BUSCA LA HISTORIA POR TITULO:</h2>
                    <br>
                    <form action='/Blog/buscar' method='GET'>
                        <div class='form-floating'>
                            <input class='form-control' type='text' name='titulo' placeholder='Ingrese un título...'>
                            <label for='titulo'>Título</label>
                        </div>
                        <input type='submit' value='BUSCAR' class='btn btn-dark mt-3'>
                        <button type='button' class='btn btn-dark position-relative mt-3 mx-2'>
                            <a href='{% url "Inicio" %}' style='color: white;'>IR A INICIO</a>
                        </button>
                    </form>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </main> -->

{% if error %}

    <p style='color: red; text-align: center'>{{error}}</p>

{% endif %}

{% if posteo %}
    <br>
    <br>
    <div class='container px-4 px-lg-5'>
        <div class='row gx-4 gx-lg-5 justify-content-center'>
            <div class='col-md-10 col-lg-8 col-xl-7'>
                <div class='card mb-5'>
                    <div class='card-body'>
                        <div class='small text-muted'>{{posteo.fecha}}</div>
                        <h2 class='card-title'>{{posteo.titulo}}</h2>
                        <p class='card-text'>{{posteo.autor}}</p>
                        <a class='btn btn-dark' href='{% url "Posteo" posteo.titulo%}'>LEER →</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endif %}

{% endblock %}

ProyectoFinal/Blog/templates/Blog/editarPosteo.html
{% extends 'Blog/padre.html' %}

{% load static %}

{% block contenido_avatar %}

    <img class='mx-2' height='50px' src='{{url}}' alt='Avatar' title='Avatar'>

{% endblock %}

{% block titulo_header %}
    <div class="tituloHeader">
        <span class='subheading'>Transforma la historia</span>
    </div>
    <div class="parrafo">
        <p>Si queres modificar algo podras hacerlo desde aqui!</p>
        <p>Si continuas la historia de otra persona, sugerimos que indiques de inicio a fin tu agregado mediante una autoria.</p>
    </div>
{% endblock %}

{% block contenido_principal %}

    {% if editForm.errors %}

        <p style='color: red; text-align: center'>¡Datos incorrectos!</p>

    {% endif %}
    
        <div class='container px-4 px-lg-5'>
            <div class='row gx-4 gx-lg-5 justify-content-center'>
                <div class='col-md-10 col-lg-8 col-xl-7'>
                    <div class='my-5'>
                        <form action='' method='POST' enctype='multipart/form-data' class='form-floating'>{% csrf_token %}
                            <table>
                                {{editForm.as_table}}
                            </table>
                            <input type='submit' value='EDITAR' class='btn btn-dark mt-3 mx-1'>
                            <button type='button' class='btn btn-dark position-relative mt-3'>
                                <a href='{% url "listaPosteos" %}' style='color: white;'>VOLVER</a>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

ProyectoFinal/Blog/templates/Blog/editarUsuario.html
{% extends 'Blog/padre.html' %}

{% load static %}

{% block contenido_avatar %}

    <img class='mx-2' height='50px' src='{{url}}' alt='Avatar' title='Avatar'>

{% endblock %}

{% block titulo_header %}

    <div class="tituloHeader">
        <span class='subheading'>Edita Tu Usuario</span>
    </div>
    <div class="parrafo">
        <p>En esta seccion podras cambiar tu nombre de usuario</p>
    </div>
{% endblock %}

{% block contenido_principal %}

    {% if editForm.errors %}

        <p style='color: red; text-align: center'>¡Datos incorrectos!</p>

    {% endif %}
<br>
<br>
<br>
    <div class='mb-4'>
        <div class='container px-4 px-lg-5'>
            <p>Username: {{user.username}}</p>
            <p>Mail: {{user.email}}</p> 
            <p>Nombre: {{user.first_name}}</p>
            <p>Apellido: {{user.last_name}}</p>
        </div>
    </div>

        <div class='mb-4'>
            <div class='container px-4 px-lg-5'>
                <br>
                <br>
                <form class='form-group text-center' action='' method='POST'>{% csrf_token %}
                    <table class='table'>
                        {{editForm.as_p}}
                    </table>
                    <input type='submit' value='EDITAR' class='btn btn-dark'>
                    <button type='button' class='btn btn-dark position-relative'>
                        <a href='{% url "listaPosteos" %}' style='color: white;'>IR A INICIO</a>
                    </button>
                </form>
            </div>
        </div>

{% endblock %}

ProyectoFinal/Blog/templates/Blog/hacerPosteo.html
{% extends 'Blog/padre.html' %}

{% load static %}

{% block contenido_avatar %}

    <img class='mx-2' height='50px' src='{{url}}' alt='Avatar' title='Avatar'>

{% endblock %}

{% block titulo_header %}
    <div class="tituloHeader">
        <span class='subheading'>Escribe aqui</span>
    </div>
    <div class="parrafo">
        <p>Abajo encontraras los campos para comenzar a escribir tu historia. </p>
    </div>
{% endblock %}

{% block contenido_principal %}

    {% if miPosteo.errors %}

        <p style='color: red; text-align: center'>¡Datos incorrectos!</p>

    {% endif %}

        <div class='container px-4 px-lg-5'>
            <div class='row gx-4 gx-lg-5 justify-content-center'>
                <div class='col-md-10 col-lg-8 col-xl-7'>
                    <div class='my-5'>
                        <form action='' method='POST' enctype='multipart/form-data' class='form-floating'>{% csrf_token %}
                            <table>
                                {{miPosteo.as_table}}
                            </table>
                            <input type='submit' value='POSTEAR' class='btn btn-dark mt-3 mx-3'>
                            <button type='button' class='btn btn-dark position-relative mt-3'>
                                <a href='{% url "listaPosteos" %}' style='color: white;'>VOLVER</a>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

ProyectoFinal/Blog/templates/Blog/login.html
{% extends 'Blog/padre.html' %}

{% load static %}

{% block contenido_avatar %}

    <img class='mx-2' height='50px' src='{{url}}' alt='Avatar' title='Avatar'>

{% endblock %}

{% block titulo_header %}

<div class="tituloHeader">
    <span class='subheading'>Inicia Sesión</span>
</div>
<div class="parrafo">
    <p></p>
</div>

{% endblock %}

{% block contenido_principal %}
<br>
<br>
    <div class='mb-4'>
        <div class='container px-4 px-lg-5'>
            <form class='form-group text-center' action='' method='POST'>{% csrf_token %}
                <table class='table'>
                    {{form.as_p}}
                </table>
                {% if errors %}
                    {% for error in errors %}
                        <p style='margin-top: -32px;' class='alert alert-danger'>{{error}}</p>
                    {% endfor %}
                {% endif %}
                <input type='submit' value='INICIAR SESIÓN' class='btn btn-dark'>
                <p>¿No tenés una cuenta? !Registrate ahora!</p>
                <a class='btn btn-dark' href='{% url "Register" %}'>CREAR CUENTA</a>
                <button type='button' class='btn btn-dark position-relative mx-2'>
                    <a href='{% url "Inicio" %}' style='color: white;'>IR A INICIO</a>
                </button>
            </form>
        </div>
    </div>

{% endblock %}

ProyectoFinal/Blog/templates/Blog/padre.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        {% load static %}
        <meta charset='utf-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no' />

        {% if id == 1 %}
            <title>P R E F A C I O - Inicio</title>

        {% elif id == 2 %}
            <title>P R E F A C I O - Sobre Nosotros</title>

        {% elif id == 3 %}
            <title>P R E F A C I O - Postear</title>

        {% elif id == 4 %}
            <title>P R E F A C I O - Buscar Posteo</title>

        {% elif id == 5 %}
            <title>P R E F A C I O  - Login</title>

        {% elif id == 6 %}
            <title>P R E F A C I O  - Registro</title>

        {% elif id == 7 %}
            <title>P R E F A C I O  - Lista de Posteos</title>

        {% elif id == 8 %}
            <title>P R E F A C I O  - Editar Posteo</title>

        {% elif id == 9 %}
            <title>P R E F A C I O  - Editar Usuario</title>

        {% elif id == 10 %}
            <title>P R E F A C I O  - Agregar Imagen</title>

        {% endif %}

        <!-- Favicon-->
        <link rel='icon' type='image/x-icon' href='{% static "Blog/assets/iconbook.png" %}' />
        <!-- Font Awesome icons -->
        <script src='https://use.fontawesome.com/releases/v6.1.0/js/all.js' crossorigin='anonymous'></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <!-- Google fonts-->
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css' />
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css' />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href='{% static "Blog/css/styles.css" %}' rel='stylesheet' />
        <link href='{% static "Blog/css/estilos.css" %}' rel='stylesheet' />
    </head>
    <body>
        <!-- Navigation-->
        <div class="banner">
            <nav class='navbar navbar-expand-lg' id='mainNav'>
                <div class='container px-4 px-lg-5'>
                    <a class='navbar-brand' href='{% url "Inicio" %}'><img src='{% static "Blog/assets/img/logo.png" %}' alt='Logo' title='Logo' height='80px' width='80px'></a>
                    <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarResponsive' aria-controls='navbarResponsive' aria-expanded='false' aria-label='Toggle navigation'>
                        <i class='fas fa-bars'></i>
                    </button>
                    <div class='collapse navbar-collapse' id='navbarResponsive'>
                        <ul class='navbar-nav ms-auto py-4 py-lg-0'>
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4' href='{% url "Inicio" %}'>Inicio</a></li>
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4' href='{% url "sobreNosotros" %}'>Sobre Nosotros</a></li>
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4' href='{% url "listaPosteos" %}'>Escritos</a></li>
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4' href='{% url "Buscar" %}'>Buscar</a></li>
                            {% if not user.is_authenticated %}
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4 btn btn-dark mx-2' href='{% url "Register" %}'>Registro</a></li>
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4 btn btn-dark mx-2' href='{% url "Login" %}'>Login</a></li>
                            {% endif %}
                            {% if user.is_authenticated %}
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4 text-center ' href='{% url "agregarAvatar" %}'>User {{user.username}}</a></li>
                            <li class='mx-1'>
                            {% with first_image=user.avatar_set.first %} 
                                {% if first_image %} 
                                    <a href='{% url "agregarAvatar" %}'>
                                    <img class="avatar" src='{{ first_image.imagen.url }}' height='60px'>
                                {% endif %}
                            {% endwith %}
                            </li>   
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4 mx-2' href='{% url "editarUsuario" %}'><i class="bi bi-person-circle"></i> Edit</a></li>
                            <li class='nav-item'><a class='nav-link px-lg-3 py-3 py-lg-4 mx-2' href='{% url "Logout" %}'><i class="bi bi-person-circle"></i> Logout</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page Header-->
            <header>
                <div class='container position-relative px-4 px-lg-5'>
                    <div class='row gx-4 gx-lg-5 justify-content-center'>
                        <div class='col-md-10 col-lg-8 col-xl-7'>
                            <div class=''>
                                {% block titulo_header %}

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        </div>
        <!-- Main Content-->

        {% block contenido_principal %}

        {% endblock %}

        <!-- Footer-->
        <footer class='border-top'>
            <div class='container px-4 px-lg-5'>
                <div class='row gx-4 gx-lg-5 justify-content-center'>
                    <div class='col-md-10 col-lg-8 col-xl-7'>
                        <ul class='list-inline text-center'>
                            <li class='list-inline-item'>
                                <br>
                                <br>
                                <a href='#!'>
                                    <span class='fa-stack fa-lg'>
                                        <i class='fab fa-twitter'></i>
                                    </span>
                                </a>
                            </li>
                            <li class='list-inline-item'>
                                <a href='#!'>
                                    <span class='fa-stack fa-lg'>
                                        <i class='fab fa-facebook-f'></i>
                                    </span>
                                </a>
                            </li>
                            <li class='list-inline-item'>
                                <a href='#!'>
                                    <span class='fa-stack fa-lg'>
                                        <i class='fab fa-instagram'></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class='small text-center text-muted fst-italic'>Copyright &copy; P R E F A C I O </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js'></script>
        <!-- Core theme JS-->
        <script src='{% static "Blog/js/scripts.js" %}'></script>
    </body>
</html>